### PR TITLE
Make mypy a dev dependency

### PR DESCRIPTION
**Pull request by rschwanhold**
fixes #263

### CODE REVIEW

**Comment by rschwanhold** [comment]
I dont't understand why the order of many lines changes. All I did was to run `poetry update mypy`

**Comment by jstriebel** [comment]
> I dont't understand why the order of many lines changes. All I did was to run `poetry update mypy`

True, that's weird. Did you maybe use a different mypy version?

**Review by jstriebel — APPROVED** [review]
LGTM :+1:

**Comment by rschwanhold** [comment]
> > I dont't understand why the order of many lines changes. All I did was to run `poetry update mypy`
> 
> True, that's weird. Did you maybe use a different mypy version?

No, I used `0.770`

**Pull request merged**
