### PR TITLE
Support adding a layer via symlink

### PR DESCRIPTION
**Pull request by rschwanhold**
- add method to the `Dataset` class for adding layers of foreign datasets via a symlink
- fixes: #201

### CODE REVIEW

**Comment by rschwanhold** [comment]
The properties of the layer are copied to the `datasource-properties.json` of the new dataset. 
Example:
`ds1` is the original dataset with a layer `color`.
`ds2` has a symlink to the `color` layer of `ds1`
If you write data to `color` through `ds2`, then only the bounding box in the properties of `ds2` will be updated.
Is this a problem?

**Comment by philippotto** [comment]
> The properties of the layer are copied to the `datasource-properties.json` of the new dataset.
> Example:
> `ds1` is the original dataset with a layer `color`.
> `ds2` has a symlink to the `color` layer of `ds1`
> If you write data to `color` through `ds2`, then only the bounding box in the properties of `ds2` will be updated.
> Is this a problem?

As I see it, there are three options:
- Try to be clever and update the `datasource-properties.json` in both datasets --> However, this won't work, if one mutates the original dataset (because that dataset doesn't know it's being linked to).
- Try to forbid mutating a symlinked layer --> However, this also does not cover the case where the original dataset is mutated.
- Don't do anything and let the user be responsible for what they are doing.

Since option 1 and 2 are not perfect, I'd simply go with option 3. Until now, we also simply symlink layers and don't really care about the problem of keeping the bounding box consistent. Since we usually don't mutate the symlinked layer, anyway, this should be fine in my opinion.

However, maybe somebody also can also weigh in with their opinion? For example, @jstriebel ?

**Review by philippotto — COMMENTED** [review]
Cool PR! Code looks good and :+1: for the test. Let's wait for another opinion regarding your last question, though.

**Comment by jstriebel** [comment]
Agree with @philippotto :+1: Leaving this to the user would probably be fine!

**Review by philippotto — APPROVED** [review]
Nice one :sunglasses:

**Pull request merged**
